# Generated by Django 4.2.3 on 2025-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=4)),
                ('code', models.CharField(max_length=4)),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
